FIND_PATH(CVD_INCLUDE_DIR cvd/vision.h /usr/include /usr/local/include /opt/ros/include)
FIND_LIBRARY(CVD_LIBRARY cvd [/usr/lib /usr/local/lib] /opt/ros/lib)

IF (CVD_INCLUDE_DIR AND CVD_LIBRARY)
   SET(CVD_FOUND TRUE)
ENDIF (CVD_INCLUDE_DIR AND CVD_LIBRARY)

IF (CVD_FOUND)
   IF (NOT CVD_FIND_QUIETLY)
      MESSAGE(STATUS "Found CVD: ${CVD_INCLUDE_DIR}")
      MESSAGE(STATUS "Found CVD: ${CVD_LIBRARY}")
   ENDIF (NOT CVD_FIND_QUIETLY)
ELSE (CVD_FOUND)
   IF (CVD_FIND_REQUIRED)
#MESSAGE(STATUS "Could not find CVD")
      MESSAGE(STATUS "Obtain CVD via cvs:")
      MESSAGE(STATUS "$ export CVS_RSH=ssh")
      MESSAGE(STATUS "$ cvs -z3 -d:pserver:anonymous@cvs.savannah.nongnu.org:/sources/libcvd co -D \"Mon May 11 16:29:26 BST 2009\" libcvd")
      MESSAGE(STATUS "Install CVD:")
      MESSAGE(STATUS "$ export CXXFLAGS=-D_REENTRANT")
      MESSAGE(STATUS "$ ./configure --without-ffmpeg")
      MESSAGE(STATUS "\# make && make install")
      MESSAGE(FATAL_ERROR "Could not find CVD")
   ENDIF (CVD_FIND_REQUIRED)
ENDIF (CVD_FOUND)
